### ISSUE TITLE
Exercise 4.1 does not compile - undefined reference to `assert_failed'

### ISSUE THREAD

**Issue by stehgold** [geoffreymbrown/STM32-Template#3]
Hi,
I was working my way through your book and hoping to learn how to program STM32s using the gcc tool chain. Turns out my geekyness is not high enough... Trying to compile the modified blinky from exercise 4.1 throws a lot of "undefined reference to assert_failed" from STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c

I've downloaded the library from STM just yesterday. I found two suggested 'fixes' for that, none of them made it compile.

Helpless,
Stephan

**Comment by ghassenhalleb** [comment]
I had the same problem too, adding ifdef USE_FULL_ASSERT di solve my problem.
Thank you!
